### ISSUE TITLE
[BUG] Selfhosted Docker Library Never Loads, Stuck on "Please Wait"

### ISSUE THREAD

**Issue by DylanIerley** [snuffyDev/Beatbump#176]
**Describe the bug**
Upon entering the library tab on PC (firefox, chromium) or iOS (safari), the library loads infinitely and never serves liked songs or playlists. Interestingly, the export data json does correctly contain the liked songs and other data, but it isn't loaded somehow, including when I try to import it.

**To Reproduce**
1. Go to library
2. Click see "Please Wait"
3. Infinite Loading

**Expected behavior**
Playlists and liked songs load after some reasonable period

**Docker**
 - Running with volume mounted to /app for persistence

**Desktop**
 - OS: Arch Linux, iOS
 - Browser: Tested on Degooogled-Chromium and Firefox

**Smartphone**
 - Device: iPhone 12
 - OS: iOS 16.5
 - Browser Safari
 
**Additional Context**
I've attached an exported json if that reveals any issues or helps in any way, I also noticed the following error in my docker logs which seems to occur some of the times that this issue occurs:

`Error: Not found: /.well-known/gpc.json

    at _ (file:///app/build/server/index.js:1078:14294)

    at resolve (file:///app/build/server/index.js:1078:12567)

    at Object.a [as handle] (file:///app/build/server/chunks/hooks.server-c722afdc.js:1:731)

    at Fe (file:///app/build/server/index.js:1078:12536)

true false Dark`

[beatbump-dbxouZCpkp6.txt](https://github.com/snuffyDev/Beatbump/files/11821649/beatbump-dbxouZCpkp6.txt)

**Comment by snuffyDev** [comment]
Sorry I haven't responded -- I'm working on this now

**Comment by Colon101** [comment]
this is still happening to me
