### ISSUE TITLE
[BUG] Playlists are empty

### ISSUE THREAD

**Issue by BrightDV** [snuffyDev/Beatbump#205]
Hello,
Another bug report here.

**Describe the bug**
Playlists render blank screen

**To Reproduce**
1. Go to Library
2. Open a local playlist
4. See error.

**Expected behavior**
See the songs.

**Screenshots**
![image](https://github.com/snuffyDev/Beatbump/assets/92821484/83e5f7d9-149c-440c-be36-51ca55e1ca6e)

Not device-specific.

**Additional context**
Full error stack:
```
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'contentRating' in 1
    at Ce (InfoBox.3cbed3dc.js:1:7066)
    at Ot (index.e91c457c.js:4:3955)
    at new He (InfoBox.3cbed3dc.js:1:10250)
    at te (11.8893b075.js:1:2666)
    at Object.p (11.8893b075.js:1:6193)
    at dt (scheduler.c5ba8d05.js:1:10555)
    at _t (scheduler.c5ba8d05.js:1:10208)
Ce @ InfoBox.3cbed3dc.js:1
Ot @ index.e91c457c.js:4
He @ InfoBox.3cbed3dc.js:1
te @ 11.8893b075.js:1
p @ 11.8893b075.js:1
dt @ scheduler.c5ba8d05.js:1
_t @ scheduler.c5ba8d05.js:1
```

**Comment by BrightDV** [comment]
It seems that your latest commit fixed this issue, thanks!
