### ISSUE TITLE
Web keep reloading

### ISSUE THREAD

**Issue by martadinata666** [snuffyDev/Beatbump#70]
I tried deploy locally,
1. Clone git repo
2. npm install
3. edit .env.EXAMPLE
```
VITE_DOMAIN="localhost"
VITE_SITE_URL="http://localhost"
```
4. npm run dev

Then i access through browser, the web load and keep reload for 2 or 3 secs, the error show was
```
Cannot read properties of undefined (reading 'url')
TypeError: Cannot read properties of undefined (reading 'url')
    at index.svelte:44:61
    at Object.$$render (/home/debian/beatbump/node_modules/svelte/internal/index.js:1745:22)
    at Object.default (root.svelte:43:47)
    at Object.default (/src/routes/__layout.svelte:77:43)
    at eval (/src/lib/components/Wrapper/Wrapper.svelte:32:74)
    at Object.$$render (/home/debian/beatbump/node_modules/svelte/internal/index.js:1745:22)
    at eval (/src/routes/__layout.svelte:75:181)
    at Object.$$render (/home/debian/beatbump/node_modules/svelte/internal/index.js:1745:22)
    at root.svelte:37:45
    at $$render (/home/debian/beatbump/node_modules/svelte/internal/index.js:1745:22)
[] undefined {}
[] undefined {}
[] undefined {}
```
It keep repeating for every web reload.

How can i deploy in local correctly, thanks.

**Comment by martadinata666** [comment]
Seems, there another branch `rewrite` thatt work correctly.
